### PR TITLE
Paper trail gem

### PR DESCRIPTION
**Pull request by Naghmehd**
Installed paper trail gem
Add a versions table to your database. Did bundle exec rails generate paper_trail:install
bundle exec rake db:migrate
Added has_paper_trail to the horses model, users model, sessions model and participants model.

### CODE REVIEW

**Comment by jah2488** [comment]
Oh no tests are failing @Naghmehd. It looks like the issue is that the `rake db:migrate` run was not added and committed. Can you make sure to run `rake db:migrate` again locally, add and commit all the changes from that and push to this same branch? 

That will update the PR and re-run the tests.

**Comment by jah2488** [comment]
The tests are still failing and it looks like the issue is that paper trail does not work with the clearance gem we are using. So can you go ahead and remove the paper trail from the user model and repush?

**Comment by Naghmehd** [comment]
Wait don't merge 
I removed everything . I removed all of it ..

**Comment by Naghmehd** [comment]
@jah2488 I removed the gem and code from all models and it passed but after re adding the gem and adding code has_paper_trail to horses, sessions and participants model the test failed again.

**Comment by jah2488** [comment]
Hey @Naghmehd I'm going to close this PR for now and put the story on hold. Nothing wrong with the code or anything you've done, but on further investigation into this Paper Trail Gem, it may need to be added later in a specific way. So feel free to just checkout master again and throw away this branch and grab another story. 

Sorry

**Pull request closed without merging**
